### ISSUE TITLE
2022.11.33 - Sensor Parsing Errors

### ISSUE THREAD

**Issue by virtzilla** [kw123/Hue-Lights-Indigo-plugin#19]
Loaded up 2022.11.33. Logs filling up with errors around parsing sensor data, much like the initial two included below (they seem to fire every second or two).

```
path To files:          =================
   Hue Lights                      detailed logging        /Library/Application Support/Perceptive Automation/Indigo 2022.1/Logs/com.nathansheldon.indigoplugin.HueLights/plugin.log
   Hue Lights                      testing logging levels, for info only: 
   Hue Lights                      logger  enabled for     INFO           ==> TEST ONLY 
   Hue Lights Warning              logger  enabled for     WARNING        ==> TEST ONLY 
   Hue Lights Error                logger  enabled for     ERROR          ==> TEST ONLY 
   Hue Lights Error                logger  enabled for     CRITICAL       ==> TEST ONLY 
   Started plugin "Hue Lights 2022.11.33"
   Hue Lights                      debug areas:[]
   Hue Lights                      bridge lights groups scenes users resources rules schedules sensors hostIds / user names ------------------- ip Numbers ---- BridgeIds-------
   Hue Lights                      #0         47     52     69   200        15   180        12      72 eKZfuqKfR1VZ0bQBq27UT8BVXhC4OHmBK18f3QOw 10.1.1.83       001788FFFEA8EB67
   Hue Lights                      #1          2      1      9    64         9    74        14      15 KtZynLv1ZU4gwBknjmWjj01zNkd5odsP608vP6tk 10.1.1.84       001788FFFEA252CB
   Hue Lights                      ... initialized
   Hue Lights                      Hue Lights  "Yard - Hue Motion Sensor - Luminance" received: sensor update to 766 lux
   Hue Lights Error                
Traceback (most recent call last):
  File "plugin.py", line 7336, in parseOneHueSensorData
    if logChanges: self.indiLOG.log(20, "Hue Lights  \"{}\" received:{}  {}".format(device.name), shortcut['buttontexts'][lastButtonPressed],  shortcut['textSuffix'][eventType+1])
IndexError: Replacement index 1 out of range for positional args tuple
   Hue Lights Error                
Traceback (most recent call last):
  File "plugin.py", line 7336, in parseOneHueSensorData
    if logChanges: self.indiLOG.log(20, "Hue Lights  \"{}\" received:{}  {}".format(device.name), shortcut['buttontexts'][lastButtonPressed],  shortcut['textSuffix'][eventType+1])
IndexError: Replacement index 1 out of range for positional args tuple
   Hue Lights                      Hue Lights  "Name Redacted Room- Hue Motion
```

**Comment by kw123** [comment]
for the time being switch off all logging in config. I shall post a version today that fixes it .
 it is one misplaced “)” in a format statement for a device type&event type I don’t have installed.


Karl


ps the next version can:

- add new devices to the bridge
- delete devices from bridge
- rename them
- stet on/off,

those are  all option available on a bridge that you can do  to / with devices on the bridge.

**Comment by kw123** [comment]
v2022.12.36 @ 2022-07-20

should fix that

**Comment by virtzilla** [comment]
It did.

**Comment by kw123** [comment]
are the messages just once or ongoing?

Re set on-off
There is now a menu option to disable / enable switches / sensors on the bridge. 
So if you are home you could disable a motion sensor and then actions on the bridge get disabled. Eg  light on if motion 
detected. 

Karl
